version: '3.8'

services:
  database:
    container_name: db
    image: postgres:12.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - .db:/var/lib/postgresql/data
    command: go run main.go users.go -b 0.0.0.0

volumes:
  db: