version: '3.8'

services:
  web:
      build: .
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=db
      ports:
        - 5432:5432
      volumes:
        - .:/Users/marin/GO/src/github.com/SWE-2023-Spring/dbTest
      command: go run api -b 0.0.0.0

